### ISSUE TITLE
[POSSIBLE BUG/ERROR]

### ISSUE THREAD

**Issue by rajat-np** [code-fi/react-native-news-app#1]
I followed the exact instructions given on the readme. But I get error when I run `react-native run-android`. I  have a physical device connected and I can successfully run my app on it. 
`blizzard@blizzard-g4:~/react-native-news-app$ react-native run-android
Scanning folders for symlinks in /home/blizzard/react-native-news-app/node_modules (15ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
`

**Comment by f0wu5u** [comment]
This may be caused by adb not able to connect with your device, make sure you have USB Debugging enabled on your device and also android SDK set-up correctly on your PC.

Try running `adb devices -ls` to check if your device is connected successfully. If connected then you can run `gradlew.bat assembleDebug` in the android directory of your project root. This will generate a debug APK  that you can install on your device, APK can be found at `android\app\build\outputs\apk`

**Comment by rajat-np** [comment]
@code-fi I already mentioned that I can run react-native run-android and install & debug in my phone with the app I am developing. But not with your project. I am kinda new to react native.

**Comment by f0wu5u** [comment]
Okay after cloning the project, you follow these steps

run
`npm install`

then

`react-native run-android`

**Comment by rajat-np** [comment]
Man, the problem still persists.

**Comment by f0wu5u** [comment]
Can you copy the entire error message here ?
Because my latest build for this project was successful

**Comment by rajat-np** [comment]
blizzard@blizzard-g4:~/react-native-news-app$  react-native run-android 
Scanning folders for symlinks in /home/blizzard/react-native-news-app/node_modules (15ms) 
JS server already running. 
Building and installing the app on the device (cd android && ./gradlew installDebug)... 
**Could not install the app on the device, read the error above for details. Make sure you have an Android emulator running or a device connected and have set up your Android development environment: https://facebook.github.io/react-native/docs/android-setup.html**

**Comment by f0wu5u** [comment]
Was the debug APK generated successfully ?
Because it's seems build was successful but adb issues couldn't make a successful installation

I have even push my latest built this includes tabs and more features than the old...

**Comment by rajat-np** [comment]
I think the problem lies with react-native run-android command, since I was able to generate a debug apk with gradlew assembleDebug.

**Comment by rajat-np** [comment]
gradlew didn't had permission to execute, I gave it the permission and the problem is fixed. The debug is installed in my device. But it gets crashed everytime when I open it.

**Comment by rajat-np** [comment]
Yes , there was problem with permission of gradlew. I fixed it and I am able to run react-native run-android. But now I get this error.
*** What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE**

**Comment by rajat-np** [comment]
I fixed all the issues , and the debug is now installed in my device.

**Comment by rajat-np** [comment]
the problem was related to permsion given to gradlew. chmod +x gradlew fixed the issue.

**Comment by rajat-np** [comment]
I had the debug installed in my device , but it fails to load any thing. It gets stuck here. 
https://drive.google.com/open?id=1d52eWLaLbbi8sCjoM_Q5X5er0GFH5x0h

**Comment by varunchandran333** [comment]
I am getting error while taking build..
---------------------------------------------------
The development server returned response error code: 404

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"message":"Cannot find entry file index.android.js in any of the roots: [\"/home/varun/Documents/SampleProjects/React/myapp\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}
-------------------------------------------------------------------------------------------------------------------------------------------
This is in the Old structure, DO you know how to convert that to new structure with App.js and single index.js

**Comment by rajat-np** [comment]
@varunchandran333 you need to update your environment. What version of react and react native you have presently ?
